### ISSUE TITLE
Console Spam

### ISSUE THREAD

**Issue by PinkAxolotl01** [PandaaaPlays/AutomaticBroadcast#14] opened 2024-09-28 17:42 UTC
[15:31:00 WARN]: [AutomaticBroadcast] Task #111 for AutomaticBroadcast v1.7.1 generated an exception
java.lang.ArrayIndexOutOfBoundsException: Index 0 out of bounds for length 0
        at org.bukkit.craftbukkit.CraftServer.dispatchCommand(CraftServer.java:1014) ~[paper-1.21.1.jar:1.21.1-40-2fdb2e9]
        at org.bukkit.craftbukkit.CraftServer.dispatchCommand(CraftServer.java:1004) ~[paper-1.21.1.jar:1.21.1-40-2fdb2e9]
        at AutomaticBroadcast-1.7.1.jar/ca.pandaaa.automaticbroadcast.broadcast.BroadcastManager.sendBroadcast(BroadcastManager.java:72) ~[AutomaticBroadcast-1.7.1.jar:?]
        at AutomaticBroadcast-1.7.1.jar/ca.pandaaa.automaticbroadcast.broadcast.BroadcastManager.sendRandomBroadcast(BroadcastManager.java:52) ~[AutomaticBroadcast-1.7.1.jar:?]
        at AutomaticBroadcast-1.7.1.jar/ca.pandaaa.automaticbroadcast.broadcast.BroadcastManager.sendRandomBroadcast(BroadcastManager.java:47) ~[AutomaticBroadcast-1.7.1.jar:?]
        at AutomaticBroadcast-1.7.1.jar/ca.pandaaa.automaticbroadcast.broadcast.BroadcastManager.automaticBroadcast(BroadcastManager.java:36) ~[AutomaticBroadcast-1.7.1.jar:?]
        at AutomaticBroadcast-1.7.1.jar/ca.pandaaa.automaticbroadcast.AutomaticBroadcast$1.run(AutomaticBroadcast.java:179) ~[AutomaticBroadcast-1.7.1.jar:?]
        at org.bukkit.craftbukkit.scheduler.CraftTask.run(CraftTask.java:86) ~[paper-1.21.1.jar:1.21.1-40-2fdb2e9]
        at org.bukkit.craftbukkit.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:475) ~[paper-1.21.1.jar:1.21.1-40-2fdb2e9]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1726) ~[paper-1.21.1.jar:1.21.1-40-2fdb2e9]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:473) ~[paper-1.21.1.jar:1.21.1-40-2fdb2e9]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1598) ~[paper-1.21.1.jar:1.21.1-40-2fdb2e9]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1304) ~[paper-1.21.1.jar:1.21.1-40-2fdb2e9]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:330) ~[paper-1.21.1.jar:1.21.1-40-2fdb2e9]
        at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
[15:43:38 INFO]: AXO_PinkAxolotl lost connection: Disconnected
[15:43:38 INFO]: [-]
[15:46:00 WARN]: [AutomaticBroadcast] Task #111 for AutomaticBroadcast v1.7.1 generated an exception

**Comment by PandaaaPlays** [comment] 2024-09-28 18:23
Hey @PinkAxolotl01, I was not able to reproduce this error. Could you provide more information, such as your broadcasts.yml file and your config.yml file please?

**Comment by PandaaaPlays** [comment] 2024-09-28 18:40
Hey @PinkAxolotl01, this indeed was an error that would only occur on Paper servers... It is now fixed in 1.7.2 (sorry for the inconvenience).

For curious : The issue was coming from any empty "console-command" in the broadcasts.yml file. Basically, paper cannot make the console send "".

**Closed as completed by PandaaaPlays** 2024-09-28 18:40 UTC
